### ISSUE TITLE
Mismatch profile pic

### ISSUE THREAD

**Issue by BLG75** [difrad/truman_esl_empathy#1]
**Describe the bug**
In the 'What's On Wendy's Plate?' at the top of the feed, when you click one of her six pictures her profile picture at the top of the post changes to a man.
**To Reproduce**
1. Go to 'What's On Wendy's Plate?'
2. Click on one of the posts
3. Note her name and profile photo on the top of the post

**Expected behavior**
Profile picture at the top of the post should be the same as the picture on her account, not guy in red shirt

**Screenshots**
![screen shot 2018-07-18 at 2 13 58 pm](https://user-images.githubusercontent.com/41390315/42900282-83c176fc-8a96-11e8-8939-8a6bf22476e1.png)

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [Chrome]
 - Version [10.12.6]

**Smartphone (please complete the following information):**
N/a

**Additional context**

**Comment by difrad** [comment]
fixed
