### ISSUE TITLE
Flagging on a User Post - Doesn't Disappear

### ISSUE THREAD

**Issue by zuvichcj** [difrad/truman_esl_empathy#3]
**Describe the bug**
When you flag a post on a user's page and then reload the page the post is still visible.

<img width="772" alt="screen shot 2018-07-18 at 2 29 21 pm" src="https://user-images.githubusercontent.com/23707897/42900464-ff6a10ac-8a96-11e8-970d-551dc0389b2d.png">

**Smartphone (please complete the following information):**
 - Device: Macbook Pro
 - Browser: Chrome

**Comment by difrad** [comment]
I just checked this and it works just fine. Let me know if still an issue
