### ISSUE TITLE
Double Post

### ISSUE THREAD

**Issue by BLG75** [difrad/truman_esl_empathy#5]
**Describe the bug**
When making a new post, it posts twice.
**To Reproduce**
Make a new post

**Expected behavior**
Only posts to feed once

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [Chrome]
 - Version [10.12]

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by difrad** [comment]
Fixed this issue it latest push
