### ISSUE TITLE
Notified You've Read This Coming In Late

### ISSUE THREAD

**Issue by BLG75** [difrad/truman_esl_empathy#9]
**Describe the bug**
For some posts, the notification bar that you've read this is immediately present the second the post appears on your screen. For others, you have to scroll down until the post has very nearly disappeared into the top of the screen before the notification fades slowly in. 

**To Reproduce**
Just scrolling around

**Expected behavior**
Notification should consistently appear as soon as you viewed the post

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [iOS
 - Browser [Chrome]
 - Version [10.12]

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by difrad** [comment]
This may not be a bug. "You've read this" will stay on a post if you are read it before. I can't currently reproduce this error.
